name: Deploy Theme on Develop Push

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Theme
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Theme
        uses: easingthemes/ssh-deploy@main
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-host: ${{ secrets.HOST_DNS }}
          remote-user: ${{ secrets.USERNAME }}
          target-dir: /var/www/html/wp-content/themes
